<?php

namespace Database\Seeders;

use App\Models\Food;
use Illuminate\Database\Seeder;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $foods = [
            // Karbohidrat
            [
                'name' => 'Nasi Putih',
                'category' => 'Karbohidrat',
                'icon' => 'rice_bowl',
                'serving_size' => 100,
                'calories' => 130,
                'protein' => 2.7,
                'fat' => 0.3,
                'carbohydrate' => 28,
                'fiber' => 0.4,
                'sugar' => 0,
            ],
            [
                'name' => 'Nasi Merah',
                'category' => 'Karbohidrat',
                'icon' => 'rice_bowl',
                'serving_size' => 100,
                'calories' => 111,
                'protein' => 2.6,
                'fat' => 0.9,
                'carbohydrate' => 23,
                'fiber' => 1.8,
                'sugar' => 0,
            ],
            [
                'name' => 'Bubur Nasi',
                'category' => 'Karbohidrat',
                'icon' => 'soup_kitchen',
                'serving_size' => 100,
                'calories' => 46,
                'protein' => 0.8,
                'fat' => 0.1,
                'carbohydrate' => 10,
                'fiber' => 0.1,
                'sugar' => 0,
            ],
            [
                'name' => 'Kentang Rebus',
                'category' => 'Karbohidrat',
                'icon' => 'breakfast_dining',
                'serving_size' => 100,
                'calories' => 87,
                'protein' => 1.9,
                'fat' => 0.1,
                'carbohydrate' => 20,
                'fiber' => 1.8,
                'sugar' => 0.8,
            ],
            [
                'name' => 'Roti Gandum',
                'category' => 'Karbohidrat',
                'icon' => 'bakery_dining',
                'serving_size' => 30,
                'calories' => 69,
                'protein' => 3.6,
                'fat' => 1.1,
                'carbohydrate' => 12,
                'fiber' => 1.9,
                'sugar' => 1.4,
            ],

            // Protein
            [
                'name' => 'Telur Rebus',
                'category' => 'Protein',
                'icon' => 'egg',
                'serving_size' => 50,
                'calories' => 78,
                'protein' => 6.3,
                'fat' => 5.3,
                'carbohydrate' => 0.6,
                'fiber' => 0,
                'sugar' => 0.6,
            ],
            [
                'name' => 'Ayam Kukus',
                'category' => 'Protein',
                'icon' => 'restaurant',
                'serving_size' => 100,
                'calories' => 165,
                'protein' => 31,
                'fat' => 3.6,
                'carbohydrate' => 0,
                'fiber' => 0,
                'sugar' => 0,
            ],
            [
                'name' => 'Ikan Salmon',
                'category' => 'Protein',
                'icon' => 'set_meal',
                'serving_size' => 100,
                'calories' => 208,
                'protein' => 20,
                'fat' => 13,
                'carbohydrate' => 0,
                'fiber' => 0,
                'sugar' => 0,
            ],
            [
                'name' => 'Tempe Goreng',
                'category' => 'Protein',
                'icon' => 'restaurant',
                'serving_size' => 50,
                'calories' => 96,
                'protein' => 9.5,
                'fat' => 4,
                'carbohydrate' => 7.5,
                'fiber' => 3,
                'sugar' => 0,
            ],
            [
                'name' => 'Tahu Kukus',
                'category' => 'Protein',
                'icon' => 'restaurant',
                'serving_size' => 100,
                'calories' => 76,
                'protein' => 8,
                'fat' => 4.8,
                'carbohydrate' => 1.9,
                'fiber' => 0.3,
                'sugar' => 0,
            ],
            [
                'name' => 'Ikan Teri',
                'category' => 'Protein',
                'icon' => 'set_meal',
                'serving_size' => 25,
                'calories' => 38,
                'protein' => 7.5,
                'fat' => 0.8,
                'carbohydrate' => 0,
                'fiber' => 0,
                'sugar' => 0,
            ],

            // Sayuran
            [
                'name' => 'Bayam Kukus',
                'category' => 'Sayuran',
                'icon' => 'eco',
                'serving_size' => 100,
                'calories' => 23,
                'protein' => 2.9,
                'fat' => 0.4,
                'carbohydrate' => 3.6,
                'fiber' => 2.2,
                'sugar' => 0.4,
            ],
            [
                'name' => 'Wortel Rebus',
                'category' => 'Sayuran',
                'icon' => 'eco',
                'serving_size' => 100,
                'calories' => 35,
                'protein' => 0.8,
                'fat' => 0.2,
                'carbohydrate' => 8,
                'fiber' => 3,
                'sugar' => 3.4,
            ],
            [
                'name' => 'Brokoli Kukus',
                'category' => 'Sayuran',
                'icon' => 'eco',
                'serving_size' => 100,
                'calories' => 35,
                'protein' => 2.4,
                'fat' => 0.4,
                'carbohydrate' => 7,
                'fiber' => 3.3,
                'sugar' => 1.4,
            ],
            [
                'name' => 'Labu Kuning',
                'category' => 'Sayuran',
                'icon' => 'eco',
                'serving_size' => 100,
                'calories' => 26,
                'protein' => 1,
                'fat' => 0.1,
                'carbohydrate' => 6.5,
                'fiber' => 0.5,
                'sugar' => 2.8,
            ],

            // Buah
            [
                'name' => 'Pisang',
                'category' => 'Buah',
                'icon' => 'nutrition',
                'serving_size' => 100,
                'calories' => 89,
                'protein' => 1.1,
                'fat' => 0.3,
                'carbohydrate' => 23,
                'fiber' => 2.6,
                'sugar' => 12,
            ],
            [
                'name' => 'Alpukat',
                'category' => 'Buah',
                'icon' => 'nutrition',
                'serving_size' => 100,
                'calories' => 160,
                'protein' => 2,
                'fat' => 15,
                'carbohydrate' => 9,
                'fiber' => 7,
                'sugar' => 0.7,
            ],
            [
                'name' => 'Pepaya',
                'category' => 'Buah',
                'icon' => 'nutrition',
                'serving_size' => 100,
                'calories' => 43,
                'protein' => 0.5,
                'fat' => 0.3,
                'carbohydrate' => 11,
                'fiber' => 1.7,
                'sugar' => 7.8,
            ],
            [
                'name' => 'Jeruk',
                'category' => 'Buah',
                'icon' => 'nutrition',
                'serving_size' => 100,
                'calories' => 47,
                'protein' => 0.9,
                'fat' => 0.1,
                'carbohydrate' => 12,
                'fiber' => 2.4,
                'sugar' => 9.4,
            ],
            [
                'name' => 'Apel',
                'category' => 'Buah',
                'icon' => 'nutrition',
                'serving_size' => 100,
                'calories' => 52,
                'protein' => 0.3,
                'fat' => 0.2,
                'carbohydrate' => 14,
                'fiber' => 2.4,
                'sugar' => 10,
            ],

            // Susu
            [
                'name' => 'Susu UHT',
                'category' => 'Susu',
                'icon' => 'local_drink',
                'serving_size' => 200,
                'calories' => 122,
                'protein' => 6.8,
                'fat' => 6.4,
                'carbohydrate' => 9.6,
                'fiber' => 0,
                'sugar' => 9.6,
            ],
            [
                'name' => 'Yogurt Plain',
                'category' => 'Susu',
                'icon' => 'local_drink',
                'serving_size' => 100,
                'calories' => 59,
                'protein' => 10,
                'fat' => 0.7,
                'carbohydrate' => 3.6,
                'fiber' => 0,
                'sugar' => 3.2,
            ],
            [
                'name' => 'Keju',
                'category' => 'Susu',
                'icon' => 'restaurant',
                'serving_size' => 30,
                'calories' => 120,
                'protein' => 7.5,
                'fat' => 10,
                'carbohydrate' => 0.4,
                'fiber' => 0,
                'sugar' => 0.2,
            ],
        ];

        foreach ($foods as $food) {
            Food::updateOrCreate(
                ['name' => $food['name']],
                array_merge($food, [
                    'is_active' => true,
                    'is_system' => true,
                    'created_by' => null,
                ])
            );
        }
    }
}
